### ISSUE TITLE
Clone and Install

### ISSUE THREAD

**Issue by bretonio** [akashacms/akashacms-example#2]
`node build.js" returns

```sh
module.js:457
    throw err;
    ^

Error: Cannot find module '/home/bretonio/akashacms-example/build.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
 ... which I guess just means that `build.js` is missing! No such file!

**Comment by robogeek** [comment]
The instructions were incorrect
