### ISSUE TITLE
"akashacms build" encounter error

### ISSUE THREAD

**Issue by luckypoem** [akashacms/akashacms-example#3]
hi.

root@AR:/usr/local/akashacms-example# akashacms build
it shows:
...
/usr/local/akashacms-example/node_modules/oembed/lib/oembed.js:141
	    util.pump(res, disco);
	         ^

TypeError: util.pump is not a function
    at Request.<anonymous> (/usr/local/akashacms-example/node_modules/oembed/lib/oembed.js:141:11)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/usr/local/akashacms-example/node_modules/request/request.js:986:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:551:20)
root@AR:/usr/local/akashacms-example#

how to fix it?
tks a lot

**Comment by robogeek** [comment]
Hmm.. the oembed package is probably broken now - it hasn't been updated for 5 years.

**Comment by robogeek** [comment]
I upgraded AkashaCMS so it uses oembetter rather than oembed.  

The failure existed on Node.js v6.x and not on v4.x - indicating that somewhere along the way the util.pump function had been dropped.  As I noted the oembed package hadn't been updated for 5 years and therefore still called util.pump.
